### ISSUE TITLE
Production Access

### ISSUE THREAD

**Issue by TravBradfield** [asangadev/cordova-plugin-stripe-google-pay#1]
Hey there, 

This is a great plugin and my test results were great. I've requested production access and followed all of Google's steps. I've also spoken to Google support and my is enabled & authorised for production access. However, I'm getting an error saying "Request failed: This merchant is not enabled for Google Pay".

Do you have some ideas to solve this? Is there a spot in this plugin where I can stipulate myth google merchant iD? Any help would be great. Thank you!

**Comment by asangadev** [comment]
Hi @TravBradfield 

You need to use a real device for this and not an emulator. Also, make sure you are using a signed APK

https://github.com/asangadev/cordova-plugin-stripe-google-pay#why-this-error-after-switching-to-production
