### ISSUE TITLE
Source folder is incorrect causing an error when building on linux

### ISSUE THREAD

**Issue by sergioltg** [asangadev/cordova-plugin-stripe-google-pay#2]
Hi, I'm getting an error when using this plugin in a linux machine. The folder in the plugin.xml has the wrong case causing an issue.
<source-file src="src/android/**StripeGooglePay**/StripeGooglePay.java" target-dir="src/android/**StripeGooglePay**" />

but the folder containing the src is all lower case src/android/stripegooglepay.

Would be possible to fix this issue?

Thank you.

**Comment by asangadev** [comment]
@sergioltg This plugin has only tested on OSX.
